"""
SaaS Product Analytics -- Streamlit dashboard entry point.

Run with: streamlit run dashboard/app.py
Pages live in dashboard/pages/ and are auto-discovered by Streamlit's
multipage app support.
"""

import streamlit as st

from db import run_query

st.set_page_config(page_title="SaaS Product Analytics", page_icon="\U0001F4CA", layout="wide")

st.title("SaaS Product Analytics")
st.markdown(
    """
    A synthetic SaaS dataset -- signups, funnel, retention, churn, feature
    usage, and revenue -- generated by `simulator/event_generator.py` and
    analyzed in `database/queries/*.sql`. Every chart on these pages is a
    Plotly rendering of one of those SQL queries; **the SQL is the primary
    deliverable**, this dashboard is a supporting view.

    Use the sidebar to navigate:
    - **Executive Overview** -- top-line KPIs and MRR trend
    - **User Behavior** -- acquisition, activation, feature adoption
    - **Conversion Funnel** -- signup-to-paid drop-off
    - **Retention & Churn** -- cohort retention, stickiness, churn
    """
)

totals = run_query("""
    SELECT
        (SELECT COUNT(*) FROM users)                                          AS total_users,
        (SELECT COUNT(*) FROM subscriptions WHERE status = 'active')          AS active_subscriptions,
        (SELECT COALESCE(SUM(amount), 0) FROM payments WHERE status = 'succeeded') AS lifetime_revenue
""")

col1, col2, col3 = st.columns(3)
col1.metric("Total Users", f"{totals['total_users'][0]:,}")
col2.metric("Active Subscriptions", f"{totals['active_subscriptions'][0]:,}")
col3.metric("Lifetime Revenue", f"${totals['lifetime_revenue'][0]:,.0f}")
